(let* ((org-file (expand-file-name "settings.org" user-emacs-directory))
       (el-file  (expand-file-name "settings.el"  user-emacs-directory)))
  (when (or (not (file-exists-p el-file))
            (file-newer-than-file-p org-file el-file))
    (require 'org)
    (org-babel-tangle-file org-file el-file "emacs-lisp"))
  (load-file el-file))
